FROM amazoncorretto:21
WORKDIR /app
COPY build/libs/greedy-homepage-be-0.0.1-SNAPSHOT.jar /app/greedy-homepage-be.jar
CMD ["java", "-Duser.timezone=Asia/Seoul", \
     "-Dspring.config.additional-location=/app/config/application.yml", \
     "-jar", "/app/greedy-homepage-be.jar"]
