spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greedy_homepage
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          descriptor:
            sql: TRACE
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false

swagger:
  base-url: "http://localhost:8080"
